.circleci/config.yml
CHANGELOG.md
RELEASE.md

Release version 0.0.1

---

CHANGELOG.md
Makefile

- check http reponse status code #4
- allow insecure access to kubelet api #2

Release version 0.0.2

---

Makefile

[nit] Delete unused LDFLAGS

---

CHANGELOG.md
Makefile

- Improve getting TaskID #15
- Fix to get subgruop(cgroup) for the new ARN #13

Release version 0.0.3

---

platform/ecsv3/taskmetadata/client.go
platform/ecsv3/taskmetadata/client_test.go
platform/kubernetes/kubelet/client.go
platform/kubernetes/kubelet/client_test.go

Improved error message to display request URL and response body.

Improve error message

---

script/build-and-push-dockerimage

Add a script for pushing DockerImage manually.

add build-and-push-dockerimage script for pushing Docker Image manually

---

.circleci/config.yml

Could not use `match(s, r [, a])` due to POSIX-awk in circleci/go.

Pattern matching using perl

---

CHANGELOG.md
Makefile

Release version 0.1.0

---

check/manager.go
metric/manager.go

I noticed some leakage of time.Ticker.

[nit] ensure to stop the tickers

---

agent/agent.go
config/config.go
config/config_test.go
config/loader.go
config/loader_test.go

This pull request implements a configuration for polling duration of agent config.

Implement polling duration for reloading agent config

---

Dockerfile.plugins

- install [mackerel-plugin-json](https://github.com/mackerelio/mackerel-plugin-json) via `mkr plugin install`

add mackerel-plugin-json to Docker image

---

platform/ecs/ecs.go
platform/kubernetes/kubernetes.go
spec/collector.go
spec/cpu.go
spec/cpu_test.go

- add spec/cpu.go to collect host's cpu info
- add CPUGenerator into the response of k8s/ecs platform's spec generators

Add cpu spec generator

---

CHANGELOG.md
Makefile

- Fix typo: crated_at -> created_at #64
- update CircleCI config #62
- update CircleCI config #60
- add support Amazon EKS on Amazon Fargate #58
- Remove a dependency on k8s.io/kubernetes #55
- Add cpu spec generator #54
- Add design document #53

Release version 0.3.0

---

CHANGELOG.md
Makefile

- fix config reload interrupts collecting metrics / check reports #70
- add "none" platform #71

Release version 0.3.1

---

Dockerfile

Avoid occuring sometimes connectivity alerts

diable HTTP/2

---

CHANGELOG.md
Makefile

Release version 0.4.0

---

config/loader_test.go

ref:https://app.circleci.com/jobs/github/mackerelio/mackerel-container-agent/326
```
GO111MODULE=off go get golang.org/x/lint/golint
go vet ./...
config/loader_test.go:99:4: call to (*T).Fatalf from a non-test goroutine
make: *** [Makefile:28: lint] Error 2
```
This error can be suppressed by pinning Go to 1.15 (#84), but we should fix it because we cannot pin Go forever ;-)

[nit] avoid testinggoroutine lint error in Go 1.16

---

.github/workflows/ci.yml

We will migrate GitHub Actions from CircleCI.
therefore I write an execution a tests at workflow.

test on github actions workflow

---

.github/workflows/ci.yml

Add a workflow to build docker images.
In order to check the operation, the execution conditions are commented.
In subsequent PRs, uncomment the commented out part. It also prepares login information for Docker Hub.

Add a workflow to build docker images.

---

.circleci/config.yml
.github/workflows/ci.yml

Removed verification code
Build and push alpha and release versions on GitHub Actions.

container build and push are disabled on Circle CI

---

config/config.go
config/config_test.go
config/env.go

fix parseConfig

---

Dockerfile

update from stretch to bullseye.

use bullseye

---

config/config_test.go
config/loader_test.go
platform/ecs/taskmetadata/client_test.go
platform/kubernetes/kubelet/client_test.go
platform/kubernetes/kubernetes_test.go
probe/http.go
probe/http_test.go
probe/probe_test.go
probe/tcp_test.go

I added if-err-nil statements to handle an error that is returned from functions and methods.

refactor: handle errors

---

.github/workflows/ci.yml
Makefile
cmdutil/command_test.go
config/config.go
metric/interface_test.go
platform/ecs/metric.go
platform/ecs/metric_test.go
platform/ecs/taskmetadata/client.go

golint was unmaintained so we should switch other linter.

use golangci lint

---

.github/workflows/ci.yml
Dockerfile
config/config_test.go
go.mod

upgrade Go: 1.17 -> 1.18

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/create-release-pr.yml

I enabled dependabot, and updated used actions to the latest version.

enable dependabot for github-actions ecosystem

---

cmd/mackerel-container-agent/main.go

Enable to set LogLevel by environment variable(`MACKEREL_LOG_LEVEL`)

Enable to set LogLevel by environment variable

---

Makefile
check/plugin.go
cmd/mackerel-container-agent/main.go
config/env.go
config/env_test.go
metric/plugin.go

related: https://github.com/mackerelio/mackerel-container-agent/pull/237
`MACKEREL_AGENT_CONFIG`
```yaml
apikey: "<api key>"
plugin:
metrics:
uptime:
command: mackerel-plugin-uptime
env:
FOO: "FOO BAR"
QUX: 'QUX QUUX'
checks:
fileage:
command: "check-file-age -w 240 -W 10 -c 600 -C 0 -f /go/src/app/go.sum"
env:
FOO: "FOO BAR"
QUX: 'QUX QUUX'
```

Enable to debug env

---

.github/workflows/ci.yml
.github/workflows/create-release-pr.yml
Dockerfile

Use go 1.22 in CI and Docker image.
```console
$ docker build . -f ./Dockerfile -t mackerel-container-agent
[+] Building 1.0s (22/22) FINISHED                                docker:desktop-linux
=> [internal] load build definition from Dockerfile                              0.0s
=> => transferring dockerfile: 1.81kB                                            0.0s
=> [internal] load metadata for docker.io/library/debian:bullseye-slim           0.6s
=> [internal] load metadata for docker.io/library/golang:1.22-bullseye           0.9s
=> [internal] load .dockerignore                                                 0.0s
=> => transferring context: 2B                                                   0.0s
=> [builder 1/6] FROM docker.io/library/golang:1.22-bullseye@sha256:9f880bd713b  0.0s
=> …
```

Use Go 1.22

---

.github/workflows/ci.yml
cmdutil/command_test.go
config/config.go
go.mod
go.sum

- upgrade to gopkg.in/yaml.v3
- use Go 1.24.2

Update lib, Go

---

.github/workflows/ci.yml
.github/workflows/create-release-pr.yml
Makefile
cmd/mackerel-container-agent/main.go

I did.
refs
- https://github.com/mackerelio/mackerel-agent-plugins/pull/1278
- https://github.com/mackerelio/mackerel-agent-plugins/pull/1279

Version info from vcs

---

plugins/go.mod
plugins/tools.go

Add a file to allow plugin updates with your current dependabot configuration.

fix plugins/
