agent/platform.go
platform/kubernetes/kubernetes.go
platform/kubernetes/kubernetes_test.go

- skip verifying Kubelet CA certificates with `MACKEREL_KUBERNETES_KUBELET_INSECURE_TLS`.
- access kubelet api with host ip address.

allow insecure access to kubelet api

---

platform/ecs/agent/client.go
platform/ecs/docker/client.go
platform/ecs/instance/client.go
platform/ecsawsvpc/taskmetadata/client.go
platform/kubernetes/kubelet/client.go

Because processing continues even with 401 or 403 error.

check http reponse status code

---

api/mock_client.go
platform/ecs/agent/mock_client.go
platform/ecs/docker/mock_client.go
platform/ecs/task/task_test.go
platform/ecsawsvpc/taskmetadata/mock_client.go
platform/kubernetes/kubelet/mock_client.go

Mock clients should report error when callback is not initialized by the tests.

Return callback not found error in mock clients

---

Makefile
script/cpanfile

This pull request upgrades Mackerel::ReleaseUtils to v0.2.4. Also, simply-binded variable is preferred in Makefile.
Ref: https://github.com/mackerelio/Mackerel-ReleaseUtils/pull/4

Upgrade Mackerel::ReleaseUtils

---

spec/manager_test.go

Expected 5 times update; at 10ms, 110ms, 210, 310, 410 and cancel the context at 450ms, instead of 500ms to make sure the next update will not be called.

[nit] Fix unstable tests

---

platform/ecs/task/task.go
platform/ecs/task/task_test.go

In a ECS task where the new ARN is opted-in, subgroups(cgroup) are changed.
* `current ARN`: /ecs/TASK_ID/DOCKER_ID
* `new ARN`: /ecs/CLUSTER_NAME/TASK_ID/DOCKER_ID
This pull request fix to this.
see. https://docs.aws.amazon.com/AmazonECS/latest/userguide/ecs-resource-ids.html

Fix to get subgruop(cgroup) for the new ARN

---

platform/ecs/spec.go
platform/ecs/spec_test.go
platform/ecsawsvpc/spec.go

Improve getting TaskID.
Format of Resouce in new ARN is "task/cluster-name/task-id".
see. https://docs.aws.amazon.com/AmazonECS/latest/userguide/ecs-resource-ids.html

Improve getting TaskID

---

platform/ecsv3/ecs.go
platform/ecsv3/ecs_test.go
platform/ecsv3/internal/mock_taskmetadatagetter.go
platform/ecsv3/spec_test.go

-In the ecs_v3 platform, access / task API in constructor to resolve network mode.
-The / task API returns an error if all containers associated with the task have not been created.
-Retry the request until the / task API no longer returns an error.

retry request to the "/task" API

---

agent/agent.go
agent/agent_test.go
agent/run.go

NewPlatform contains some API calls (especially in ecs_v3 platform) so we should notify signals before NewPlatform.

notify interrupt signals before creating platform

---

CHANGELOG.md
Makefile

- add build-and-push-dockerimage script for pushing Docker Image manually #26
- notify interrupt signals before creating platform #25
- retry request to the "/task" API #24
- Improve error message #22
- Use k8s packages #19
- Add banner image #20
- Support Task Metadata Endpoint v3 #17
- Support Go Modules #18

Release version 0.0.4

---

platform/ecs/agent/client.go
platform/ecs/agent/client_test.go
platform/ecs/instance/client.go
platform/ecs/instance/client_test.go
platform/ecsawsvpc/taskmetadata/client.go
platform/ecsawsvpc/taskmetadata/client_test.go
platform/ecsv3/taskmetadata/client.go
platform/ecsv3/taskmetadata/client_test.go
platform/kubernetes/kubernetes.go
platform/kubernetes/kubernetes_test.go

- Local HTTP proxy environment affect the API request.
- Fixed to not use HTTP proxy in API request.

don't use HTTP_PROXY when requesting API

---

config/config_test.go
config/probe.go
go.mod
probe/http.go
probe/http_test.go

- Local HTTP proxy environment affect the HTTP probe request.
- Fixed to not use HTTP proxy in HTTP probe request.
- Add the `proxy` item to HTTP probe configuration to use proxy in HTTP probe request.

don't use HTTP_PROXY when requesting HTTP probe

---

.circleci/config.yml
Dockerfile
Dockerfile.plugins

Provide the plugin bundled Docker image in the following `repository:tag`.
- mackerel/mackerel-container-agent:vX.Y.Z-plugins-alpha
- mackerel/mackerel-container-agent:plugins
- FROM mackerel/mackerel-container-agent:latest
- mackerel/mackerel-container-agent:vX.Y.Z-plugins

Provide the plugin bundled Docker image

---

CHANGELOG.md
Makefile

- Pattern matching using perl #39
- Refactor docker-image tag decisions #37
- fix to push plugins-alpha Docker image #36
- add Dockerfile.plugins to CircleCI workspace #34
- fix `docker build` options #32
- Provide the plugin bundled Docker image #30
- don't use HTTP_PROXY when requesting HTTP probe #29
- don't use HTTP_PROXY when requesting API #28

Release version 0.0.5

---

agent/agent.go
config/config.go
config/config_test.go
config/s3.go

- When accessing `s3: //`,  specifying a region is mandatory.
- Fix to access after resolving the specified bucket region.

Get s3 region

---

agent/agent.go
agent/agent_test.go
agent/host_resolver.go
agent/retire.go
agent/run.go

On SIGHUP signal and config changes, the agent should not retire the host, but keep posting the metrics to the previous host. But the host id, and even api key, can change due to the config change, so we have to collect the retirement callbacks at one place (not the host ids) and then fire them when the process exits. Ideally the callback can be fired when the host id is changed, but the implementation will be hard.

Delay host retirement for hangup signal and config reload

---

agent/agent_test.go

We should use os.RemoveAll to remove the test directories.

[nit] Use os.RemoveAll instead of os.Remove in the tests

---

CHANGELOG.md
Makefile

- add mackerel-plugin-json to Docker image #51
- Delay host retirement for hangup signal and config reload #49
- Implement polling duration for reloading agent config #47
- Fix missing region error when using S3 for config path #46

Release version 0.2.0

---

platform/ecs/types.go

`CreatedAt` field is encoded as `crated_at` in JSON but it will be expected as `created_at` (and maybe typo).

Fix typo: crated_at -> created_at

---

agent/platform.go
platform/none/none.go
platform/types.go

NOTE: This is only for development of container-agent itself.
Add "none" platform, which does not collect any platform-specific data such as specs and metrics of containers.
Currently testing & debugging container-agent requires platform setups, and it takes a bit time and efforts.
Using "none" platform enables us to test & debug non-platform-specific features quickly, even on local machine.

add "none" platform

---

check/manager.go
metric/manager.go

When the agent reloads configuration, it cancels the current context before restarting itself.
However, metric / check report collections are also referring to that context and can be interrupted, which causes the agent to lose some metric data points and/or report UNKNOWN status.
This PR fixes it by separating contexts for the agent itself and metric / check report collections to avoid interruptions on config reload.
Edit: This also keeps metric collections alive when the agent is stoped by other reasons (like SIGTERM).

fix config reload interrupts collecting metrics / check reports

---

CHANGELOG.md
Makefile

- [Kubernetes] Retrieve node CPU/memory capacity from local information, not from kubelet /spec #80
- add dependent: gobump #74

Release version 0.5.0

---

config/s3.go

When the S3 config loader fails to download the config, we get log message like 
```
ERROR <main> AccessDenied: Access Denied
ERROR <main> NoSuchKey: The specified key does not exist.
```
It is difficult to tell these messages comes from the S3 downloader. I think it's worth improving the error messages.

improve S3 config loader error messages

---

agent/agent.go
agent/host_resolver.go
go.mod
metric/plugin.go
probe/http.go
probe/tcp.go

Since Go 1.13, it is recommended to use `%w` to wrap the errors, instead of using `%s` or `pkg/errors`.
Ref: https://blog.golang.org/go1.13-errors

[nit] use %w verb to wrap errors

---

platform/kubernetes/kubernetes.go

Currently `NewEKSOnFargatePlatform`'s first two args are named `kubelet{Host,Port}`, but actually they are not host/port for Kubelet but for Kubernetes API.
So I'd like to change their name to avoid confusion.

[nit] Change arg name for NewEKSOnFargatePlatform

---

check/manager_test.go
metric/manager_test.go
probe/probe_test.go
spec/manager_test.go

Some tests are flaky. These tests don't be needed that trials count are same as expected count perfectly. Goroutines might be delayed woken up by Go runtime.

probe, spec: reduce the flakiness of tests

---

Dockerfile.multistage

It is separated into two files(`Dockerfile` `Dockerfile.plugins`), which hinders updating the build procedure, so integrate the contents of the files.
Also, instead of adding the generated binary separately, generate it in the procedure.
I haven't updated the CI procedure, so add it as a file with a different name.

Use multi-stage builds

---

internal/amazon-ecs-agent/agent/api/container/status/containerstatus.go

Because marshal/unmarshal methods are not implemented for `ContainerHealthStatus`, now mackerel-container-agent seems to always fail on AWS ECS if health check enabled. So I added marshal/unmarshal methods.

[bug-fix] add ContainerHealthStatus json marshal/unmarshal methods

---

agent/platform.go
platform/ecs/ecs.go
platform/ecs/ecs_test.go
platform/ecs/provider.go
platform/ecs/spec_test.go
platform/ecs/taskmetadata/testdata/metadata_external.json
platform/types.go

I want to use mackerel-container-agent with ECS Tasks running on ECS Anywhere
Now works on ECS Anywhere. There are two changes.
1. From `MACKEREL_CONTAINER_PLATFORM`, it is known to be running on ECS Anywhere.
2. (Unlike other ECS Tasks) Implemented a workaround because `AWS_EXECUTION_ENV` cannot be obtained
Mostly the same as https://mackerel.io/docs/entry/howto/install-agent/container/ecs.
Set `MACKEREL_CONTAINER_PLATFORM` to`ecs_external`.
I think this is an experimental function. There are three reasons.
1. In operation with ECS Anywhere, we have only confirmed the operation in the environment we are using.
2. mackerel-container-agent assumes that there is `AWS_EXECUTION_ENV`, but this time it did not exist, so it is forcibly avoided.
- It's a good idea to check the `launchType` that …

add support Amazon ECS Anywhere ( experimental )

---

agent/platform.go
platform/ecs/ecs.go
platform/ecs/ecs_test.go

- rename from ExecutionEnvECSAnywhere to ExecutionEnvECSExternal
- refactoring agent/platform.go

refactoring agent/platform.go

---

agent/agent_test.go
agent/host_resolver.go
config/config.go
config/config_test.go
config/loader_test.go
platform/ecs/taskmetadata/client.go
platform/kubernetes/kubelet/client.go
platform/kubernetes/kubernetes.go
platform/kubernetes/metric_test.go
platform/kubernetes/spec_test.go

I changed all functions provided in **io/ioutil** to the corresponding to.
Note: **testing.T.TempDir** is added in Go 1.15.

refactor: replace ioutil functions

---

agent/platform.go

Before:
After:
```zsh
~/Desktop/mackerel-container-agent
$ ./build/mackerel-container-agent 
2022/09/30 15:58:07 INFO <main> starting mackerel-container-agent (version:0.7.2, revision:af2cc21)
2022/09/30 15:58:07 ERROR <main> MACKEREL_CONTAINER_PLATFORM environment variable is not set
~/Desktop/mackerel-container-agent
$ export MACKEREL_CONTAINER_PLATFORM=foo
~/Desktop/mackerel-container-agent
$ ./build/mackerel-container-agent      
2022/09/30 15:58:25 INFO <main> starting mackerel-container-agent (version:0.7.2, revision:af2cc21)
2022/09/30 15:58:25 ERROR <main> "foo" platform is invalid. please check your MACKEREL_CONTAINER_PLATFORM
```

Improve `NewPlatform` error messages

---

README.md

The copyright year range is now outdated.

Remove last year from license header

---

agent/agent_test.go
cmdutil/command.go
config/env.go
docs/architecture.dot
docs/architecture.svg
platform/ecs/spec.go
platform/ecs/taskmetadata/client.go
platform/kubernetes/kubelet/client.go
platform/kubernetes/spec.go
spec/cpu.go
spec/generator.go
spec/mock_generator.go

In go 1.18 and above, we can replace `interface{}` to `any` alias for ease of understanding.

Replace interface{} to any

---

Dockerfile

`apt-key` command is now deprecated so I replaced it to `signed-by` option.
```console
$ docker build
[+] Building 38.4s (22/22) FINISHED                                                                     docker:desktop-linux
=> [internal] load build definition from Dockerfile                                                                    0.0s
=> => transferring dockerfile: 1.91kB                                                                                  0.0s
=> [internal] load metadata for docker.io/library/debian:bookworm-slim                                                 2.9s
=> [internal] load metadata for docker.io/library/golang:1.22-bookworm                                                 2.9s
=> [internal] load .dockerignore …
```

replace deprecated apt-key command on Dockerfile
